---
  - name: Install calico-typha server
    become: True
    apt:
      name: calico-typha-server
      state: present
      update_cache: yes
      cache_valid_time: 1800

  - name: Add calico-typha service
    become: True
    template:
      src: calico-typha.service.j2
      dest: /etc/systemd/system/calico-typha.service
      owner: root
      group: root
      mode: 0644
    notify: restart calico-typha

- name: Flush handlers
  meta: flush_handlers
